# A container that runs a postgres database

version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: teslo_db
    volumes:
      - ./postgres:/var/lib/postgresql/data